name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  release:
    types : [published, edited]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Generate file executables_names
        run: sh ./srcCxx/generate_names.sh
      - name: Install package
        run:  pip install xlsxwriter 
      - name: Run python script
        run: python ./srcCxx/test_script.py ./srcCxx/executables_names.txt
      - name: set user account email
        run: git config --global user.email "ariasmartinez@correo.ugr.es"
      - name: set user account name
        run: git config --global user.name "ariasmartinez"
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Interoperability checked automatically"
      - name: Push changes                               
        uses: ad-m/github-push-action@master
        with:
            force_with_lease: true
            github_token: ${{ secrets.GITHUB_TOKEN }}
