name: GitHub Actions Demo 6
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate file executables_names
        run: touch is_working.txt
      - name: Push changes                               
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
